Repository mchen132/COMS4156-TWCC, pull requests merged in 2022-10, with the labels that each got.

#6 T3 1 api post create event route ww
  .gitignore
  pom.xml
  src/main/java/com/TWCC/NycTodoServiceApplication.java
  src/main/java/com/TWCC/controller/EventController.java
  src/main/java/com/TWCC/data/Event.java
  src/main/java/com/TWCC/repository/EventRepository.java
  src/test/java/com/TWCC/controller/EventControllerTest.java
  src/test/java/com/TWCC/nyctodoservice/NycTodoServiceApplicationTests.java
Labels: enhancement

#16 Fixed testGetEvents failure and mainClass missing failure
  src/main/java/com/TWCC/NycTodoServiceApplication.java
  src/main/java/com/TWCC/controller/EventController.java
  src/test/java/com/TWCC/controller/EventControllerTest.java
Labels: bug

#18 T3 17 fix invalid tests inconsistencies with routes and readme ww
  README.md
  checkstyle-checker.xml
  src/main/java/com/TWCC/controller/EventController.java
  src/main/java/com/TWCC/data/Event.java
  src/test/java/com/TWCC/controller/EventControllerTest.java
Labels: enhancement

#19 Update EventCRUD with main
  README.md
  checkstyle-checker.xml
  reports/t3-checkstyle-report.png
  src/main/java/com/TWCC/repository/EventRepository.java
  src/main/resources/application.properties
Labels: update
